"""Source-reviewed mappings for the FastAPI tutorial test wave.

This module is data-only input for atlas integration. TestClient and generic
response behavior are Starlette 1.6.0 responsibilities; Pydantic and
application-owned behavior are called out rather than attributed to FastAPI.
"""


def _case(test_path, start, end, feature_ids, observation_selectors, rationale, **extra):
    return {
        "feature_ids": list(feature_ids),
        "observation_selectors": list(observation_selectors),
        "rationale": rationale,
        "replace_features": True,
        "supporting_sources": [
            {
                "path": test_path,
                "start_line": start,
                "end_line": end,
                "role": "test stimulus and asserted observations",
            }
        ],
        **extra,
    }


def _openapi(
    test_path,
    start,
    end,
    rationale="The function compares the generated OpenAPI document as an exact JSON snapshot.",
    **extra,
):
    feature_ids = extra.pop("feature_ids", ["openapi-docs"])
    observation_selectors = extra.pop("observation_selectors", ["http.status", "openapi.document"])
    return _case(test_path, start, end, feature_ids, observation_selectors, rationale, **extra)


def _module(supporting_sources, functions, **extra):
    return {"supporting_sources": supporting_sources, "functions": functions, **extra}


TUTORIAL_TEST_REVIEW_MAPPINGS = {
    "tests/test_tutorial/test_response_model/test_tutorial003_04.py": _module(
        [
            {
                "path": "tests/test_tutorial/test_response_model/test_tutorial003_04.py",
                "start_line": 15,
                "end_line": 17,
                "role": "invalid inferred response-model import and expected FastAPIError",
            },
            {
                "path": "docs_src/response_model/tutorial003_04_py310.py",
                "start_line": 1,
                "end_line": 11,
                "role": "route annotated as Response | dict",
            },
            {
                "path": "fastapi/utils.py",
                "start_line": 58,
                "end_line": 77,
                "role": "FastAPI converts Pydantic schema-generation failure to FastAPIError",
            },
        ],
        {
            "test_invalid_response_model": _case(
                "tests/test_tutorial/test_response_model/test_tutorial003_04.py",
                15,
                17,
                ["public-api-errors", "response-serialization"],
                [
                    "construction.outcome",
                    "construction.exception_class",
                    "construction.exception_message",
                ],
                "Importing the documented Response | dict route fails during registration with FastAPIError; a schema-v3 construction workflow now observes its outcome, class, and message.",
                stimulus_notes="The fixture executes an equivalent independently authored workload rather than importing or copying upstream tests.",
            ),
        },
        module_observation_selectors=[
            "construction.outcome",
            "construction.exception_class",
            "construction.exception_message",
        ],
    ),
    "tests/test_tutorial/test_authentication_error_status_code/test_tutorial001.py": _module(
        [
            {
                "path": "docs_src/authentication_error_status_code/tutorial001_an_py310.py",
                "start_line": 1,
                "end_line": 21,
                "role": "HTTPBearer dependency override and protected route",
            },
            {
                "path": "fastapi/security/http.py",
                "start_line": 222,
                "end_line": 285,
                "role": "FastAPI HTTPBearer credential extraction",
            },
            {
                "path": "fastapi/exceptions.py",
                "start_line": 17,
                "end_line": 60,
                "role": "FastAPI HTTPException public type",
            },
            {
                "path": "fastapi/exception_handlers.py",
                "start_line": 11,
                "end_line": 25,
                "role": "FastAPI HTTP exception response mapping",
            },
            {
                "path": "fastapi/openapi/utils.py",
                "start_line": 132,
                "end_line": 156,
                "role": "OpenAPI security scheme generation",
            },
        ],
        {
            "test_get_me": _case(
                "tests/test_tutorial/test_authentication_error_status_code/test_tutorial001.py",
                23,
                29,
                ["app-routing", "dependency-security"],
                ["http.status", "http.body.json"],
                "A valid bearer credential is extracted by FastAPI's security dependency and passed to the route. The greeting payload and returned token are application-owned values.",
            ),
            "test_get_me_no_credentials": _case(
                "tests/test_tutorial/test_authentication_error_status_code/test_tutorial001.py",
                32,
                35,
                ["dependency-security", "public-api-errors"],
                ["http.status", "http.body.json"],
                "The HTTPBearer subclass supplies its own 403 detail for missing credentials; FastAPI injects the dependency and renders the FastAPI HTTPException. The chosen 403 policy/detail is app customization.",
            ),
            "test_openapi_schema": _openapi(
                "tests/test_tutorial/test_authentication_error_status_code/test_tutorial001.py",
                38,
                66,
                "The exact OpenAPI snapshot includes the HTTP bearer security requirement; the security dependency definition is FastAPI-owned, while generated component/schema internals retain their Pydantic identity.",
                feature_ids=["openapi-docs", "dependency-security"],
                observation_selectors=["http.status", "openapi.document"],
            ),
        },
    ),
    "tests/test_tutorial/test_bigger_applications/test_main.py": _module(
        [
            {
                "path": "docs_src/bigger_applications/app_an_py310/main.py",
                "start_line": 1,
                "end_line": 23,
                "role": "application-wide dependencies, router composition, and root route",
            },
            {
                "path": "docs_src/bigger_applications/app_an_py310/dependencies.py",
                "start_line": 1,
                "end_line": 13,
                "role": "application-owned token checks and HTTPException details",
            },
            {
                "path": "docs_src/bigger_applications/app_an_py310/routers/users.py",
                "start_line": 1,
                "end_line": 18,
                "role": "users routes and application-owned response values",
            },
            {
                "path": "docs_src/bigger_applications/app_an_py310/routers/items.py",
                "start_line": 1,
                "end_line": 38,
                "role": "item routes, dependency, and application-owned errors/data",
            },
            {
                "path": "fastapi/routing.py",
                "start_line": 2889,
                "end_line": 2910,
                "role": "FastAPI APIRouter route configuration",
            },
            {
                "path": "fastapi/routing.py",
                "start_line": 3133,
                "end_line": 3155,
                "role": "FastAPI include_router composition and dependency inheritance",
            },
            {
                "path": "fastapi/openapi/utils.py",
                "start_line": 311,
                "end_line": 355,
                "role": "OpenAPI operation generation including dependency-derived parameters",
            },
            {
                "path": "fastapi/exception_handlers.py",
                "start_line": 11,
                "end_line": 25,
                "role": "FastAPI HTTP exception response mapping",
            },
        ],
        {
            "test_users_token_jessica": _case(
                "tests/test_tutorial/test_bigger_applications/test_main.py",
                21,
                24,
                ["app-routing", "dependency-security"],
                ["http.status", "http.body.json"],
                "The application-wide query-token dependency admits this request; the usernames and response body are application-owned.",
            ),
            "test_users_with_no_token": _case(
                "tests/test_tutorial/test_bigger_applications/test_main.py",
                27,
                39,
                ["request-validation", "dependency-security"],
                ["http.status", "http.body.json", "validation.error_details"],
                "FastAPI reports the missing required query token before the application dependency body runs. Pydantic supplies the missing-field detail under the pinned identity.",
            ),
            "test_users_foo_token_jessica": _case(
                "tests/test_tutorial/test_bigger_applications/test_main.py",
                42,
                45,
                ["app-routing", "dependency-security"],
                ["http.status", "http.body.json"],
                "The shared dependency admits the request and the username route returns its application-owned value.",
            ),
            "test_users_foo_with_no_token": _case(
                "tests/test_tutorial/test_bigger_applications/test_main.py",
                48,
                60,
                ["request-validation", "dependency-security"],
                ["http.status", "http.body.json", "validation.error_details"],
                "The required application-wide query dependency is missing; FastAPI/Pydantic produce the asserted 422 response.",
            ),
            "test_users_me_token_jessica": _case(
                "tests/test_tutorial/test_bigger_applications/test_main.py",
                63,
                66,
                ["app-routing", "dependency-security"],
                ["http.status", "http.body.json"],
                "The token dependency admits the route and the username is application-owned.",
            ),
            "test_users_me_with_no_token": _case(
                "tests/test_tutorial/test_bigger_applications/test_main.py",
                69,
                81,
                ["request-validation", "dependency-security"],
                ["http.status", "http.body.json", "validation.error_details"],
                "FastAPI reports the missing required application-wide query token; Pydantic owns the exact missing-field detail.",
            ),
            "test_users_token_monica_with_no_jessica": _case(
                "tests/test_tutorial/test_bigger_applications/test_main.py",
                84,
                87,
                ["dependency-security", "public-api-errors"],
                ["http.status", "http.body.json"],
                "The dependency graph runs and the app's get_query_token policy raises its custom 400. The custom status/detail are application-owned; FastAPI supplies HTTPException-to-response integration.",
            ),
            "test_items_token_jessica": _case(
                "tests/test_tutorial/test_bigger_applications/test_main.py",
                90,
                98,
                ["app-routing", "dependency-security"],
                ["http.status", "http.body.json"],
                "Router-level header validation and the global token dependency admit the request; the item dictionary is application-owned.",
            ),
            "test_items_with_no_token_jessica": _case(
                "tests/test_tutorial/test_bigger_applications/test_main.py",
                101,
                113,
                ["request-validation", "dependency-security"],
                ["http.status", "http.body.json", "validation.error_details"],
                "FastAPI reports the missing required application-wide token query parameter before endpoint execution.",
            ),
            "test_items_plumbus_token_jessica": _case(
                "tests/test_tutorial/test_bigger_applications/test_main.py",
                116,
                121,
                ["app-routing", "dependency-security"],
                ["http.status", "http.body.json"],
                "Both dependency layers pass and the route returns its application-owned item data.",
            ),
            "test_items_bar_token_jessica": _case(
                "tests/test_tutorial/test_bigger_applications/test_main.py",
                124,
                129,
                ["app-routing", "dependency-security", "public-api-errors"],
                ["http.status", "http.body.json"],
                "Route matching and dependencies succeed, then application code raises 404 for an unknown key; only FastAPI's exception-to-HTTP integration is framework behavior.",
            ),
            "test_items_plumbus_with_no_token": _case(
                "tests/test_tutorial/test_bigger_applications/test_main.py",
                132,
                146,
                ["request-validation", "dependency-security"],
                ["http.status", "http.body.json", "validation.error_details"],
                "The route request is rejected because the application-wide query token is absent; FastAPI/Pydantic own the 422 structure.",
            ),
            "test_items_with_invalid_token": _case(
                "tests/test_tutorial/test_bigger_applications/test_main.py",
                149,
                152,
                ["dependency-security", "public-api-errors"],
                ["http.status", "http.body.json"],
                "The router's application-defined X-Token rule raises a custom 400; the invalid-token decision and detail text are app-owned.",
            ),
            "test_items_bar_with_invalid_token": _case(
                "tests/test_tutorial/test_bigger_applications/test_main.py",
                155,
                158,
                ["dependency-security", "public-api-errors"],
                ["http.status", "http.body.json"],
                "The router dependency rejects the app-provided invalid header before item lookup; the custom error detail is application-owned.",
            ),
            "test_items_with_missing_x_token_header": _case(
                "tests/test_tutorial/test_bigger_applications/test_main.py",
                161,
                173,
                ["request-validation", "dependency-security"],
                ["http.status", "http.body.json", "validation.error_details"],
                "FastAPI reports a missing required header parameter in a router dependency; the exact validation error detail is Pydantic-owned.",
            ),
            "test_items_plumbus_with_missing_x_token_header": _case(
                "tests/test_tutorial/test_bigger_applications/test_main.py",
                176,
                188,
                ["request-validation", "dependency-security"],
                ["http.status", "http.body.json", "validation.error_details"],
                "FastAPI rejects the missing required router-level header before item lookup; Pydantic owns the asserted missing-field detail.",
            ),
            "test_root_token_jessica": _case(
                "tests/test_tutorial/test_bigger_applications/test_main.py",
                191,
                194,
                ["app-routing", "dependency-security"],
                ["http.status", "http.body.json"],
                "The app-wide dependency allows the root route; its greeting is application-owned.",
            ),
            "test_root_with_no_token": _case(
                "tests/test_tutorial/test_bigger_applications/test_main.py",
                197,
                209,
                ["request-validation", "dependency-security"],
                ["http.status", "http.body.json", "validation.error_details"],
                "FastAPI rejects the root request for a missing required application-wide query token.",
            ),
            "test_put_no_header": _case(
                "tests/test_tutorial/test_bigger_applications/test_main.py",
                212,
                230,
                ["request-validation", "dependency-security"],
                ["http.status", "http.body.json", "validation.error_details"],
                "The request omits both the application-wide query token and router-level required header; FastAPI reports both missing fields before app code runs.",
            ),
            "test_put_invalid_header": _case(
                "tests/test_tutorial/test_bigger_applications/test_main.py",
                233,
                236,
                ["dependency-security", "public-api-errors"],
                ["http.status", "http.body.json"],
                "The app's router dependency raises a custom 400 for the supplied invalid header; its decision and message are application-owned.",
            ),
            "test_put": _case(
                "tests/test_tutorial/test_bigger_applications/test_main.py",
                239,
                244,
                ["app-routing", "dependency-security"],
                ["http.status", "http.body.json"],
                "Dependencies pass and the PUT route returns app-owned update data.",
            ),
            "test_put_forbidden": _case(
                "tests/test_tutorial/test_bigger_applications/test_main.py",
                247,
                252,
                ["app-routing", "dependency-security", "public-api-errors"],
                ["http.status", "http.body.json"],
                "The route raises its app-defined 403 after dependencies pass; FastAPI exception response integration is exercised, while the authorization policy/detail are app-owned.",
            ),
            "test_admin": _case(
                "tests/test_tutorial/test_bigger_applications/test_main.py",
                255,
                260,
                ["app-routing", "dependency-security"],
                ["http.status", "http.body.json"],
                "The prefixed admin router and dependencies admit the request; its message is application-owned.",
            ),
            "test_admin_invalid_header": _case(
                "tests/test_tutorial/test_bigger_applications/test_main.py",
                263,
                266,
                ["dependency-security", "public-api-errors"],
                ["http.status", "http.body.json"],
                "The router-level header dependency raises its app-defined 400; detail text and token rule are application-owned.",
            ),
            "test_openapi_schema": _openapi(
                "tests/test_tutorial/test_bigger_applications/test_main.py",
                269,
                606,
                "The exact schema snapshot checks router composition, prefixes, tags, additional responses, and dependency-derived query/header parameters. Those OpenAPI integrations are FastAPI-owned; Pydantic owns model schema details.",
                feature_ids=[
                    "app-routing",
                    "dependency-security",
                    "openapi-docs",
                    "request-validation",
                ],
                observation_selectors=["http.status", "openapi.document"],
            ),
        },
    ),
    "tests/test_tutorial/test_custom_docs_ui/test_tutorial001.py": _module(
        [
            {
                "path": "docs_src/custom_docs_ui/tutorial001_py310.py",
                "start_line": 1,
                "end_line": 38,
                "role": "custom FastAPI docs routes and helper calls",
            },
            {
                "path": "fastapi/openapi/docs.py",
                "start_line": 40,
                "end_line": 65,
                "role": "FastAPI Swagger UI HTML helper",
            },
            {
                "path": "fastapi/openapi/docs.py",
                "start_line": 197,
                "end_line": 224,
                "role": "FastAPI ReDoc HTML helper",
            },
            {
                "path": "fastapi/openapi/docs.py",
                "start_line": 301,
                "end_line": 307,
                "role": "FastAPI OAuth2 redirect HTML helper",
            },
        ],
        {
            "test_swagger_ui_html": _case(
                "tests/test_tutorial/test_custom_docs_ui/test_tutorial001.py",
                23,
                27,
                ["openapi-docs"],
                ["docs.response.status", "docs.response.body.bytes"],
                "The custom FastAPI docs endpoint returns generated Swagger HTML with externally hosted JS/CSS references.",
                contract_gate="The test checks two URL substrings, not the complete HTML body; precise parity needs a body-contains projection rather than exact docs.response.body.bytes.",
                stimulus_notes="HTMLResponse framing is generic Starlette behavior; the asserted helper-generated HTML/configuration is FastAPI docs behavior.",
            ),
            "test_swagger_ui_oauth2_redirect_html": _case(
                "tests/test_tutorial/test_custom_docs_ui/test_tutorial001.py",
                31,
                34,
                ["openapi-docs"],
                ["docs.response.status", "docs.response.body.bytes"],
                "The custom route returns FastAPI's Swagger OAuth2 redirect HTML helper output.",
                contract_gate="The test checks for one HTML substring, not the complete body; precise parity needs a body-contains projection.",
            ),
            "test_redoc_html": _case(
                "tests/test_tutorial/test_custom_docs_ui/test_tutorial001.py",
                38,
                41,
                ["openapi-docs"],
                ["docs.response.status", "docs.response.body.bytes"],
                "The custom ReDoc route returns helper-generated HTML configured with external JS assets.",
                contract_gate="The test checks for one asset URL substring, not the complete HTML body; precise parity needs a body-contains projection.",
            ),
            "test_api": _case(
                "tests/test_tutorial/test_custom_docs_ui/test_tutorial001.py",
                45,
                48,
                ["app-routing"],
                ["http.status", "http.body.json"],
                "The route is reached and returns a greeting constructed by application code; the personalized message is not FastAPI-owned behavior.",
            ),
        },
    ),
    "tests/test_tutorial/test_custom_docs_ui/test_tutorial002.py": _module(
        [
            {
                "path": "docs_src/custom_docs_ui/tutorial002_py310.py",
                "start_line": 1,
                "end_line": 41,
                "role": "custom FastAPI docs routes, static mount, and helper calls",
            },
            {
                "path": "fastapi/openapi/docs.py",
                "start_line": 40,
                "end_line": 65,
                "role": "FastAPI Swagger UI HTML helper",
            },
            {
                "path": "fastapi/openapi/docs.py",
                "start_line": 197,
                "end_line": 224,
                "role": "FastAPI ReDoc HTML helper",
            },
            {
                "path": "fastapi/openapi/docs.py",
                "start_line": 301,
                "end_line": 307,
                "role": "FastAPI OAuth2 redirect HTML helper",
            },
            {
                "path": "fastapi/staticfiles.py",
                "start_line": 1,
                "end_line": 1,
                "role": "StaticFiles is a Starlette re-export",
            },
        ],
        {
            "test_swagger_ui_html": _case(
                "tests/test_tutorial/test_custom_docs_ui/test_tutorial002.py",
                23,
                27,
                ["openapi-docs"],
                ["docs.response.status", "docs.response.body.bytes"],
                "The docs endpoint returns FastAPI-generated Swagger HTML configured with local static asset paths.",
                contract_gate="The test checks JS/CSS URL substrings, not full HTML equality; precise parity needs a body-contains projection.",
                stimulus_notes="The test does not request the static files; StaticFiles serving is Starlette-owned and not observed here.",
            ),
            "test_swagger_ui_oauth2_redirect_html": _case(
                "tests/test_tutorial/test_custom_docs_ui/test_tutorial002.py",
                31,
                34,
                ["openapi-docs"],
                ["docs.response.status", "docs.response.body.bytes"],
                "The custom route returns FastAPI's Swagger OAuth2 redirect HTML helper output.",
                contract_gate="The test checks for one HTML substring, not complete body equality; precise parity needs a body-contains projection.",
            ),
            "test_redoc_html": _case(
                "tests/test_tutorial/test_custom_docs_ui/test_tutorial002.py",
                38,
                41,
                ["openapi-docs"],
                ["docs.response.status", "docs.response.body.bytes"],
                "The custom ReDoc route returns helper-generated HTML configured with local static asset paths.",
                contract_gate="The test checks for an asset URL substring, not full HTML equality; precise parity needs a body-contains projection.",
            ),
            "test_api": _case(
                "tests/test_tutorial/test_custom_docs_ui/test_tutorial002.py",
                45,
                48,
                ["app-routing"],
                ["http.status", "http.body.json"],
                "The route is reached and returns a greeting constructed by application code; the personalized message is not FastAPI-owned behavior.",
            ),
        },
    ),
    "tests/test_tutorial/test_custom_response/test_tutorial001.py": _module(
        [
            {
                "path": "docs_src/custom_response/tutorial001_py310.py",
                "start_line": 1,
                "end_line": 9,
                "role": "deprecated UJSONResponse route configuration",
            },
            {
                "path": "fastapi/responses.py",
                "start_line": 39,
                "end_line": 66,
                "role": "FastAPI UJSONResponse implementation and deprecation",
            },
            {
                "path": "fastapi/routing.py",
                "start_line": 375,
                "end_line": 400,
                "role": "FastAPI response-class integration",
            },
            {
                "path": "fastapi/openapi/utils.py",
                "start_line": 585,
                "end_line": 647,
                "role": "FastAPI OpenAPI document generation",
            },
        ],
        {
            "test_get_custom_response": _case(
                "tests/test_tutorial/test_custom_response/test_tutorial001.py",
                23,
                26,
                ["response-serialization"],
                ["http.status", "http.body.json"],
                "The route returns JSON through the deprecated UJSONResponse class. The test suppresses its deprecation warning, so it is not evidence about warning emission.",
            ),
            "test_openapi_schema": _openapi(
                "tests/test_tutorial/test_custom_response/test_tutorial001.py",
                30,
                52,
                "The exact OpenAPI snapshot records the declared JSON response class's documented media type/schema.",
            ),
        },
    ),
    "tests/test_tutorial/test_custom_response/test_tutorial001b.py": _module(
        [
            {
                "path": "docs_src/custom_response/tutorial001b_py310.py",
                "start_line": 1,
                "end_line": 9,
                "role": "deprecated ORJSONResponse route and direct response construction",
            },
            {
                "path": "fastapi/responses.py",
                "start_line": 69,
                "end_line": 98,
                "role": "FastAPI ORJSONResponse implementation and deprecation",
            },
            {
                "path": "fastapi/routing.py",
                "start_line": 375,
                "end_line": 400,
                "role": "FastAPI response-class integration",
            },
            {
                "path": "fastapi/openapi/utils.py",
                "start_line": 585,
                "end_line": 647,
                "role": "FastAPI OpenAPI document generation",
            },
        ],
        {
            "test_get_custom_response": _case(
                "tests/test_tutorial/test_custom_response/test_tutorial001b.py",
                18,
                21,
                ["response-serialization"],
                ["http.status", "http.body.json"],
                "The endpoint returns an ORJSONResponse instance. Deprecation warnings are suppressed, and serialization details of the response class remain response-library behavior.",
            ),
            "test_openapi_schema": _openapi(
                "tests/test_tutorial/test_custom_response/test_tutorial001b.py",
                25,
                47,
                "The exact OpenAPI snapshot checks the JSON response documentation for a direct ORJSONResponse return.",
            ),
        },
    ),
    "tests/test_tutorial/test_custom_response/test_tutorial002_tutorial003_tutorial004.py": _module(
        [
            {
                "path": "docs_src/custom_response/tutorial002_py310.py",
                "start_line": 1,
                "end_line": 18,
                "role": "declared HTMLResponse with returned text",
            },
            {
                "path": "docs_src/custom_response/tutorial003_py310.py",
                "start_line": 1,
                "end_line": 19,
                "role": "direct HTMLResponse return without declared response class",
            },
            {
                "path": "docs_src/custom_response/tutorial004_py310.py",
                "start_line": 1,
                "end_line": 23,
                "role": "declared HTMLResponse and direct response instance",
            },
            {
                "path": "fastapi/routing.py",
                "start_line": 375,
                "end_line": 400,
                "role": "FastAPI response-class integration",
            },
            {
                "path": "fastapi/openapi/utils.py",
                "start_line": 585,
                "end_line": 647,
                "role": "FastAPI OpenAPI document generation",
            },
        ],
        {
            "test_get_custom_response": _case(
                "tests/test_tutorial/test_custom_response/test_tutorial002_tutorial003_tutorial004.py",
                38,
                41,
                ["response-serialization"],
                ["http.status", "http.body.bytes"],
                "The variants return an exact HTML body, either via a declared response_class or a direct HTMLResponse. The HTML body is example content; generic response framing is Starlette-owned.",
            ),
            "test_openapi_schema": _openapi(
                "tests/test_tutorial/test_custom_response/test_tutorial002_tutorial003_tutorial004.py",
                44,
                71,
                "The snapshot distinguishes documented response_class media types from a directly returned Response, which FastAPI does not infer into the same response schema.",
                feature_ids=["openapi-docs", "response-serialization"],
                observation_selectors=["http.status", "openapi.document"],
            ),
        },
    ),
    "tests/test_tutorial/test_custom_response/test_tutorial005.py": _module(
        [
            {
                "path": "docs_src/custom_response/tutorial005_py310.py",
                "start_line": 1,
                "end_line": 9,
                "role": "PlainTextResponse route configuration",
            },
            {
                "path": "fastapi/routing.py",
                "start_line": 375,
                "end_line": 400,
                "role": "FastAPI response-class integration",
            },
            {
                "path": "fastapi/openapi/utils.py",
                "start_line": 585,
                "end_line": 647,
                "role": "FastAPI OpenAPI document generation",
            },
        ],
        {
            "test_get": _case(
                "tests/test_tutorial/test_custom_response/test_tutorial005.py",
                9,
                12,
                ["response-serialization"],
                ["http.status", "http.body.bytes"],
                "The declared PlainTextResponse route returns the example's exact text; text response encoding/framing is generic Starlette behavior.",
            ),
            "test_openapi_schema": _openapi(
                "tests/test_tutorial/test_custom_response/test_tutorial005.py",
                15,
                39,
                "The exact OpenAPI snapshot checks the plain-text media type inferred from the declared response class.",
            ),
        },
    ),
    "tests/test_tutorial/test_custom_response/test_tutorial006.py": _module(
        [
            {
                "path": "docs_src/custom_response/tutorial006_py310.py",
                "start_line": 1,
                "end_line": 9,
                "role": "direct RedirectResponse route",
            },
            {
                "path": "fastapi/routing.py",
                "start_line": 357,
                "end_line": 372,
                "role": "FastAPI route status handling",
            },
            {
                "path": "fastapi/openapi/utils.py",
                "start_line": 585,
                "end_line": 647,
                "role": "FastAPI OpenAPI document generation",
            },
        ],
        {
            "test_get": _case(
                "tests/test_tutorial/test_custom_response/test_tutorial006.py",
                9,
                12,
                ["response-serialization"],
                ["http.status", "http.headers.ordered"],
                "The direct RedirectResponse produces the asserted 307 and Location value.",
                contract_gate="The test asserts only the Location header; an exact ordered-header comparison would overstate it, so a single-header predicate is required.",
                constraints={"starlette_testclient": {"follow_redirects": False}},
                stimulus_notes="RedirectResponse defaults and TestClient redirect policy belong to Starlette; FastAPI returns the direct response.",
            ),
            "test_openapi_schema": _openapi(
                "tests/test_tutorial/test_custom_response/test_tutorial006.py",
                15,
                37,
                "The exact OpenAPI snapshot documents the route's default success response even though the handler returns a redirect response directly.",
                feature_ids=["openapi-docs", "response-serialization"],
                observation_selectors=["http.status", "openapi.document"],
            ),
        },
    ),
    "tests/test_tutorial/test_custom_response/test_tutorial006b.py": _module(
        [
            {
                "path": "docs_src/custom_response/tutorial006b_py310.py",
                "start_line": 1,
                "end_line": 9,
                "role": "declared RedirectResponse route with string return",
            },
            {
                "path": "fastapi/routing.py",
                "start_line": 357,
                "end_line": 372,
                "role": "FastAPI route status handling",
            },
            {
                "path": "fastapi/openapi/utils.py",
                "start_line": 585,
                "end_line": 647,
                "role": "FastAPI OpenAPI document generation",
            },
        ],
        {
            "test_redirect_response_class": _case(
                "tests/test_tutorial/test_custom_response/test_tutorial006b.py",
                9,
                12,
                ["response-serialization"],
                ["http.status", "http.headers.ordered"],
                "The declared RedirectResponse class turns the route's returned URL string into the asserted redirect response.",
                contract_gate="The test asserts only the Location header; an exact ordered-header comparison would overstate it, so a single-header predicate is required.",
                constraints={"starlette_testclient": {"follow_redirects": False}},
                stimulus_notes="RedirectResponse encoding and TestClient redirect policy belong to Starlette; FastAPI selects the declared response class.",
            ),
            "test_openapi_schema": _openapi(
                "tests/test_tutorial/test_custom_response/test_tutorial006b.py",
                15,
                32,
                "The exact OpenAPI snapshot records the response status code from the declared RedirectResponse class.",
                feature_ids=["openapi-docs", "response-serialization"],
                observation_selectors=["http.status", "openapi.document"],
            ),
        },
    ),
    "tests/test_tutorial/test_custom_response/test_tutorial010.py": _module(
        [
            {
                "path": "docs_src/custom_response/tutorial010_py310.py",
                "start_line": 1,
                "end_line": 9,
                "role": "FastAPI default HTML response class and route",
            },
            {
                "path": "fastapi/applications.py",
                "start_line": 353,
                "end_line": 368,
                "role": "FastAPI default_response_class configuration",
            },
            {
                "path": "fastapi/routing.py",
                "start_line": 375,
                "end_line": 400,
                "role": "FastAPI route response-class selection",
            },
            {
                "path": "fastapi/openapi/utils.py",
                "start_line": 585,
                "end_line": 647,
                "role": "FastAPI OpenAPI document generation",
            },
        ],
        {
            "test_get_custom_response": _case(
                "tests/test_tutorial/test_custom_response/test_tutorial010.py",
                20,
                23,
                ["response-serialization"],
                ["http.status", "http.body.bytes"],
                "The app-level default response class turns the route's app-owned HTML string into the exact asserted body.",
            ),
            "test_openapi_schema": _openapi(
                "tests/test_tutorial/test_custom_response/test_tutorial010.py",
                26,
                50,
                "The exact OpenAPI snapshot checks that FastAPI documents the app-level default response class as text/html.",
                feature_ids=["openapi-docs", "response-serialization"],
                observation_selectors=["http.status", "openapi.document"],
            ),
        },
    ),
    "tests/test_tutorial/test_cors/test_tutorial001.py": _module(
        [
            {
                "path": "docs_src/cors/tutorial001_py310.py",
                "start_line": 1,
                "end_line": 24,
                "role": "FastAPI CORS import, finite allowed-origin list, middleware registration, and route",
            },
            {
                "path": "docs/en/docs/tutorial/cors.md",
                "start_line": 35,
                "end_line": 77,
                "role": "documented FastAPI middleware setup and Starlette preflight/simple-request behavior",
            },
            {
                "path": "docs/en/docs/tutorial/cors.md",
                "start_line": 83,
                "end_line": 88,
                "role": "explicit boundary note that FastAPI re-exports CORS middleware from Starlette",
            },
            {
                "path": "fastapi/middleware/cors.py",
                "start_line": 1,
                "end_line": 1,
                "role": "FastAPI convenience import re-exports Starlette CORSMiddleware",
            },
            {
                "path": "fastapi/applications.py",
                "start_line": 42,
                "end_line": 42,
                "role": "FastAPI subclasses Starlette and inherits add_middleware",
            },
            {
                "path": "fastapi/applications.py",
                "start_line": 1033,
                "end_line": 1068,
                "role": "FastAPI places the inherited user middleware registrations in its middleware stack",
            },
            {
                "path": "starlette/applications.py",
                "start_line": 104,
                "end_line": 107,
                "role": "Starlette implementation inherited by FastAPI for add_middleware registration",
            },
            {
                "path": "starlette/middleware/cors.py",
                "start_line": 78,
                "end_line": 96,
                "role": "Starlette CORS dispatch for non-HTTP, origin-free, preflight, and simple requests",
            },
            {
                "path": "starlette/middleware/cors.py",
                "start_line": 107,
                "end_line": 150,
                "role": "Starlette CORS preflight allow checks and 200/400 response selection",
            },
            {
                "path": "starlette/middleware/cors.py",
                "start_line": 152,
                "end_line": 179,
                "role": "Starlette CORS response-header handling for simple requests",
            },
        ],
        {
            "test_cors": _case(
                "tests/test_tutorial/test_cors/test_tutorial001.py",
                6,
                37,
                ["middleware-integrations"],
                ["http.status", "http.headers.ordered", "http.body.bytes"],
                "The test observes an allowed preflight, an allowed simple request, and a request without Origin. FastAPI supplies the middleware import and app registration surface; add_middleware is inherited from Starlette, which owns the CORS request and response decisions. The independent recipe also probes the documented disallowed-origin and rejected-method paths without asserting the upstream test's expected outputs.",
                stimulus_notes="The workload independently recreates the documented app configuration. Its ASGI inputs are based on the assertions plus separate source-cited probes for disallowed origins and a non-standard preflight method.",
            ),
        },
    ),
    "tests/test_tutorial/test_dataclasses/test_tutorial001.py": _module(
        [
            {
                "path": "docs_src/dataclasses_/tutorial001_py310.py",
                "start_line": 1,
                "end_line": 19,
                "role": "standard dataclass request body and endpoint",
            },
            {
                "path": "fastapi/dependencies/utils.py",
                "start_line": 951,
                "end_line": 1005,
                "role": "FastAPI request-body extraction and field validation integration",
            },
            {
                "path": "fastapi/routing.py",
                "start_line": 301,
                "end_line": 342,
                "role": "FastAPI response-model serialization integration",
            },
            {
                "path": "fastapi/openapi/utils.py",
                "start_line": 585,
                "end_line": 647,
                "role": "FastAPI OpenAPI document generation",
            },
        ],
        {
            "test_post_item": _case(
                "tests/test_tutorial/test_dataclasses/test_tutorial001.py",
                24,
                32,
                ["request-validation", "response-serialization"],
                ["http.status", "http.body.json"],
                "FastAPI accepts the dataclass body and returns it through the route. Dataclass construction/coercion and its field defaults are Pydantic/dataclasses behavior under the pinned identities.",
            ),
            "test_post_invalid_item": _case(
                "tests/test_tutorial/test_dataclasses/test_tutorial001.py",
                35,
                47,
                ["request-validation"],
                ["http.status", "http.body.json", "validation.error_details"],
                "FastAPI surfaces a 422 for the invalid dataclass body; the float parsing error type/message/details are Pydantic-owned.",
            ),
            "test_openapi_schema": _openapi(
                "tests/test_tutorial/test_dataclasses/test_tutorial001.py",
                50,
                142,
                "The snapshot checks FastAPI's request/response operation document for a dataclass model; generated model schema details remain Pydantic-owned.",
                feature_ids=["openapi-docs", "request-validation", "response-serialization"],
                observation_selectors=["http.status", "openapi.document"],
            ),
        },
    ),
    "tests/test_tutorial/test_dataclasses/test_tutorial002.py": _module(
        [
            {
                "path": "docs_src/dataclasses_/tutorial002_py310.py",
                "start_line": 1,
                "end_line": 25,
                "role": "dataclass with default_factory and response_model route",
            },
            {
                "path": "fastapi/routing.py",
                "start_line": 301,
                "end_line": 342,
                "role": "FastAPI response-model serialization integration",
            },
            {
                "path": "fastapi/openapi/utils.py",
                "start_line": 585,
                "end_line": 647,
                "role": "FastAPI OpenAPI document generation",
            },
        ],
        {
            "test_get_item": _case(
                "tests/test_tutorial/test_dataclasses/test_tutorial002.py",
                24,
                33,
                ["app-routing", "response-serialization"],
                ["http.status", "http.body.json"],
                "FastAPI applies the declared dataclass response_model to the route result. The returned item values/default behavior are example data and Pydantic/dataclasses serialization semantics.",
            ),
            "test_openapi_schema": _openapi(
                "tests/test_tutorial/test_dataclasses/test_tutorial002.py",
                36,
                88,
                "The exact OpenAPI snapshot checks the dataclass response schema and route metadata; Pydantic owns the generated model schema details.",
                feature_ids=["openapi-docs", "response-serialization"],
                observation_selectors=["http.status", "openapi.document"],
            ),
        },
    ),
    "tests/test_tutorial/test_dataclasses/test_tutorial003.py": _module(
        [
            {
                "path": "docs_src/dataclasses_/tutorial003_py310.py",
                "start_line": 1,
                "end_line": 54,
                "role": "Pydantic dataclasses, nested response models, and routes",
            },
            {
                "path": "fastapi/dependencies/utils.py",
                "start_line": 951,
                "end_line": 1005,
                "role": "FastAPI request-body extraction and validation integration",
            },
            {
                "path": "fastapi/routing.py",
                "start_line": 301,
                "end_line": 342,
                "role": "FastAPI response-model serialization integration",
            },
            {
                "path": "fastapi/openapi/utils.py",
                "start_line": 585,
                "end_line": 647,
                "role": "FastAPI OpenAPI document generation",
            },
        ],
        {
            "test_post_authors_item": _case(
                "tests/test_tutorial/test_dataclasses/test_tutorial003.py",
                24,
                36,
                ["request-validation", "response-serialization"],
                ["http.status", "http.body.json"],
                "FastAPI parses nested Pydantic dataclass request items and filters the returned Author response model. The nested dataclass semantics/defaults are Pydantic-owned.",
            ),
            "test_get_authors": _case(
                "tests/test_tutorial/test_dataclasses/test_tutorial003.py",
                39,
                67,
                ["app-routing", "response-serialization"],
                ["http.status", "http.body.json"],
                "FastAPI filters nested returned data through list[Author]; all author/item values and defaulting semantics originate in the example and Pydantic.",
            ),
            "test_openapi_schema": _openapi(
                "tests/test_tutorial/test_dataclasses/test_tutorial003.py",
                70,
                210,
                "The exact document checks FastAPI's route/request/response schema assembly for nested Pydantic dataclasses.",
                feature_ids=["openapi-docs", "request-validation", "response-serialization"],
                observation_selectors=["http.status", "openapi.document"],
            ),
        },
    ),
    "tests/test_tutorial/test_encoder/test_tutorial001.py": _module(
        [
            {
                "path": "docs_src/encoder/tutorial001_py310.py",
                "start_line": 1,
                "end_line": 22,
                "role": "Pydantic Item, route, and jsonable_encoder database update",
            },
            {
                "path": "fastapi/encoders.py",
                "start_line": 129,
                "end_line": 206,
                "role": "FastAPI jsonable_encoder signature and options",
            },
            {
                "path": "fastapi/dependencies/utils.py",
                "start_line": 951,
                "end_line": 1005,
                "role": "FastAPI request body validation integration",
            },
            {
                "path": "fastapi/openapi/utils.py",
                "start_line": 585,
                "end_line": 647,
                "role": "FastAPI OpenAPI document generation",
            },
        ],
        {
            "test_put": _case(
                "tests/test_tutorial/test_encoder/test_tutorial001.py",
                28,
                45,
                ["request-validation", "python-data-encoding"],
                ["http.status", "python.attribute_value"],
                "FastAPI validates the Item request and jsonable_encoder converts it to JSON-compatible data stored by the example. The fake_db key/value are application-owned state; datetime encoding is the encoder behavior being exercised.",
                stimulus_notes="The test inspects application state rather than an HTTP response body; it does not test response serialization.",
            ),
            "test_put_invalid_data": _case(
                "tests/test_tutorial/test_encoder/test_tutorial001.py",
                48,
                70,
                ["request-validation"],
                [
                    "http.status",
                    "http.body.json",
                    "validation.error_details",
                    "python.attribute_value",
                ],
                "FastAPI rejects the invalid timestamp before the endpoint mutates fake_db. Pydantic supplies the exact datetime parsing error; database state is application-owned.",
            ),
            "test_openapi_schema": _openapi(
                "tests/test_tutorial/test_encoder/test_tutorial001.py",
                73,
                212,
                "The exact snapshot checks the endpoint's generated request/response document; model-field JSON Schema details are Pydantic-owned.",
                feature_ids=["openapi-docs", "request-validation"],
                observation_selectors=["http.status", "openapi.document"],
            ),
        },
    ),
    "tests/test_tutorial/test_events/test_tutorial001.py": _module(
        [
            {
                "path": "docs_src/events/tutorial001_py310.py",
                "start_line": 1,
                "end_line": 16,
                "role": "startup handler populates app data and route reads it",
            },
            {
                "path": "fastapi/routing.py",
                "start_line": 2520,
                "end_line": 2537,
                "role": "FastAPI router lifespan context wiring",
            },
            {
                "path": "fastapi/routing.py",
                "start_line": 6415,
                "end_line": 6445,
                "role": "FastAPI deprecated on_event registration",
            },
            {
                "path": "fastapi/openapi/utils.py",
                "start_line": 585,
                "end_line": 647,
                "role": "FastAPI OpenAPI document generation",
            },
        ],
        {
            "test_events": _case(
                "tests/test_tutorial/test_events/test_tutorial001.py",
                14,
                18,
                ["app-routing", "websocket-lifecycle"],
                ["http.status", "http.body.json", "lifecycle.event_order"],
                "The TestClient context invokes FastAPI's registered startup event before the route reads app-owned data. Generic TestClient/lifespan transport is Starlette-owned; returned item data is app logic.",
                stimulus_notes="The test does not assert cleanup state or event ordering beyond startup-before-request.",
            ),
            "test_openapi_schema": _openapi(
                "tests/test_tutorial/test_events/test_tutorial001.py",
                21,
                100,
                "The function compares only the generated OpenAPI snapshot; entering TestClient also invokes lifespan, but no lifecycle effect is asserted.",
            ),
        },
    ),
    "tests/test_tutorial/test_events/test_tutorial002.py": _module(
        [
            {
                "path": "docs_src/events/tutorial002_py310.py",
                "start_line": 1,
                "end_line": 14,
                "role": "shutdown handler writes app-owned log output and route",
            },
            {
                "path": "fastapi/routing.py",
                "start_line": 2520,
                "end_line": 2537,
                "role": "FastAPI router lifespan context wiring",
            },
            {
                "path": "fastapi/routing.py",
                "start_line": 6415,
                "end_line": 6445,
                "role": "FastAPI deprecated on_event registration",
            },
            {
                "path": "fastapi/openapi/utils.py",
                "start_line": 585,
                "end_line": 647,
                "role": "FastAPI OpenAPI document generation",
            },
        ],
        {
            "test_events": _case(
                "tests/test_tutorial/test_events/test_tutorial002.py",
                17,
                23,
                ["app-routing", "websocket-lifecycle"],
                ["http.status", "http.body.json", "lifecycle.cleanup_effects"],
                "The route returns example data, and leaving the TestClient context runs the FastAPI shutdown handler. The log file content is application-owned; Starlette owns context-manager lifespan driving.",
                contract_gate="The shutdown assertion searches for a substring in file contents; exact file-byte comparison would overstate it, so parity needs a file-content contains projection.",
            ),
            "test_openapi_schema": _openapi(
                "tests/test_tutorial/test_events/test_tutorial002.py",
                27,
                50,
                "The function compares only the generated OpenAPI snapshot; the TestClient context's shutdown file side effect is not asserted here.",
            ),
        },
    ),
    "tests/test_tutorial/test_events/test_tutorial003.py": _module(
        [
            {
                "path": "docs_src/events/tutorial003_py310.py",
                "start_line": 1,
                "end_line": 28,
                "role": "lifespan loads and clears app-owned fake model state",
            },
            {
                "path": "fastapi/routing.py",
                "start_line": 2520,
                "end_line": 2537,
                "role": "FastAPI router lifespan context wiring",
            },
            {
                "path": "fastapi/openapi/utils.py",
                "start_line": 585,
                "end_line": 647,
                "role": "FastAPI OpenAPI document generation",
            },
        ],
        {
            "test_events": _case(
                "tests/test_tutorial/test_events/test_tutorial003.py",
                11,
                18,
                ["app-routing", "websocket-lifecycle"],
                [
                    "http.status",
                    "http.body.json",
                    "lifecycle.event_order",
                    "lifecycle.cleanup_effects",
                ],
                "The TestClient context causes the FastAPI lifespan context to load then clear the example's ml_models state; the prediction result and model function are application-owned. Starlette owns the client context driver.",
                stimulus_notes="The observed global model mapping is app state, not FastAPI-owned state; preserve the before/inside/after lifecycle boundary.",
            ),
            "test_openapi_schema": _openapi(
                "tests/test_tutorial/test_events/test_tutorial003.py",
                21,
                100,
                "The function compares only the generated OpenAPI snapshot; it does not assert the example's model load/cleanup effects.",
            ),
        },
    ),
    "tests/test_tutorial/test_extra_data_types/test_tutorial001.py": _module(
        [
            {
                "path": "docs_src/extra_data_types/tutorial001_py310.py",
                "start_line": 1,
                "end_line": 27,
                "role": "UUID, datetime, time, timedelta request fields and endpoint calculation",
            },
            {
                "path": "fastapi/dependencies/utils.py",
                "start_line": 951,
                "end_line": 1005,
                "role": "FastAPI request-body extraction and validation integration",
            },
            {
                "path": "fastapi/routing.py",
                "start_line": 301,
                "end_line": 342,
                "role": "FastAPI response serialization integration",
            },
            {
                "path": "fastapi/openapi/utils.py",
                "start_line": 585,
                "end_line": 647,
                "role": "FastAPI OpenAPI document generation",
            },
        ],
        {
            "test_extra_types": _case(
                "tests/test_tutorial/test_extra_data_types/test_tutorial001.py",
                24,
                42,
                ["request-validation", "response-serialization"],
                ["http.status", "http.body.json"],
                "FastAPI binds typed path/body inputs and serializes the route result. Pydantic owns UUID/date/time coercion and formatting; the derived date arithmetic and expected values are application logic.",
            ),
            "test_openapi_schema": _openapi(
                "tests/test_tutorial/test_extra_data_types/test_tutorial001.py",
                45,
                163,
                "The exact OpenAPI snapshot checks the generated path/body parameter schemas; Pydantic owns the individual type schema representations.",
                feature_ids=["openapi-docs", "request-validation"],
                observation_selectors=["http.status", "openapi.document"],
            ),
        },
    ),
    "tests/test_tutorial/test_extra_models/test_tutorial001_tutorial002.py": _module(
        [
            {
                "path": "docs_src/extra_models/tutorial001_py310.py",
                "start_line": 1,
                "end_line": 41,
                "role": "separate input/output/database model example",
            },
            {
                "path": "docs_src/extra_models/tutorial002_py310.py",
                "start_line": 1,
                "end_line": 39,
                "role": "inherited input/output/database model example",
            },
            {
                "path": "fastapi/dependencies/utils.py",
                "start_line": 951,
                "end_line": 1005,
                "role": "FastAPI request-body extraction and validation integration",
            },
            {
                "path": "fastapi/routing.py",
                "start_line": 301,
                "end_line": 342,
                "role": "FastAPI response-model serialization and filtering",
            },
            {
                "path": "fastapi/openapi/utils.py",
                "start_line": 585,
                "end_line": 647,
                "role": "FastAPI OpenAPI document generation",
            },
        ],
        {
            "test_post": _case(
                "tests/test_tutorial/test_extra_models/test_tutorial001_tutorial002.py",
                25,
                40,
                ["request-validation", "response-serialization"],
                ["http.status", "http.body.json"],
                "FastAPI validates the input model and filters the output through UserOut; password/hash transformation and values are application-owned, while model validation/schema semantics are Pydantic-owned.",
            ),
            "test_openapi_schema": _openapi(
                "tests/test_tutorial/test_extra_models/test_tutorial001_tutorial002.py",
                43,
                161,
                "The exact snapshot checks FastAPI's input/output model references and generated operation schema; component schema details are Pydantic-owned.",
                feature_ids=["openapi-docs", "request-validation", "response-serialization"],
                observation_selectors=["http.status", "openapi.document"],
            ),
        },
    ),
    "tests/test_tutorial/test_extra_models/test_tutorial003.py": _module(
        [
            {
                "path": "docs_src/extra_models/tutorial003_py310.py",
                "start_line": 1,
                "end_line": 33,
                "role": "response model union and application item data",
            },
            {
                "path": "fastapi/routing.py",
                "start_line": 301,
                "end_line": 342,
                "role": "FastAPI response-model serialization integration",
            },
            {
                "path": "fastapi/openapi/utils.py",
                "start_line": 585,
                "end_line": 647,
                "role": "FastAPI OpenAPI document generation",
            },
        ],
        {
            "test_get_car": _case(
                "tests/test_tutorial/test_extra_models/test_tutorial003.py",
                23,
                29,
                ["app-routing", "response-serialization"],
                ["http.status", "http.body.json"],
                "The route returns application-owned item data through a union response_model. Pydantic union matching and output shape are pinned Pydantic behavior.",
            ),
            "test_get_plane": _case(
                "tests/test_tutorial/test_extra_models/test_tutorial003.py",
                32,
                39,
                ["app-routing", "response-serialization"],
                ["http.status", "http.body.json"],
                "The route returns application-owned plane data through a union response_model; union selection and validation are Pydantic-owned.",
            ),
            "test_openapi_schema": _openapi(
                "tests/test_tutorial/test_extra_models/test_tutorial003.py",
                42,
                158,
                "The exact document snapshot checks FastAPI's operation response schema for a union response_model; JSON Schema component details are Pydantic-owned.",
                feature_ids=["openapi-docs", "response-serialization"],
                observation_selectors=["http.status", "openapi.document"],
            ),
        },
    ),
    "tests/test_tutorial/test_extra_models/test_tutorial004.py": _module(
        [
            {
                "path": "docs_src/extra_models/tutorial004_py310.py",
                "start_line": 1,
                "end_line": 20,
                "role": "list[Item] response model and app-owned item data",
            },
            {
                "path": "fastapi/routing.py",
                "start_line": 301,
                "end_line": 342,
                "role": "FastAPI response-model serialization integration",
            },
            {
                "path": "fastapi/openapi/utils.py",
                "start_line": 585,
                "end_line": 647,
                "role": "FastAPI OpenAPI document generation",
            },
        ],
        {
            "test_get_items": _case(
                "tests/test_tutorial/test_extra_models/test_tutorial004.py",
                21,
                27,
                ["app-routing", "response-serialization"],
                ["http.status", "http.body.json"],
                "The route returns a list through list[Item] response filtering; item values are application-owned and model validation/serialization details are Pydantic-owned.",
            ),
            "test_openapi_schema": _openapi(
                "tests/test_tutorial/test_extra_models/test_tutorial004.py",
                30,
                75,
                "The snapshot checks FastAPI's response_model operation schema; Item component schema is Pydantic-owned.",
                feature_ids=["openapi-docs", "response-serialization"],
                observation_selectors=["http.status", "openapi.document"],
            ),
        },
    ),
    "tests/test_tutorial/test_extra_models/test_tutorial005.py": _module(
        [
            {
                "path": "docs_src/extra_models/tutorial005_py310.py",
                "start_line": 1,
                "end_line": 8,
                "role": "dict[str, float] response model and route",
            },
            {
                "path": "fastapi/routing.py",
                "start_line": 301,
                "end_line": 342,
                "role": "FastAPI response-model serialization integration",
            },
            {
                "path": "fastapi/openapi/utils.py",
                "start_line": 585,
                "end_line": 647,
                "role": "FastAPI OpenAPI document generation",
            },
        ],
        {
            "test_get_items": _case(
                "tests/test_tutorial/test_extra_models/test_tutorial005.py",
                21,
                24,
                ["app-routing", "response-serialization"],
                ["http.status", "http.body.json"],
                "The route returns its app-owned dictionary through dict[str, float] response_model validation and serialization.",
            ),
            "test_openapi_schema": _openapi(
                "tests/test_tutorial/test_extra_models/test_tutorial005.py",
                27,
                57,
                "The snapshot checks FastAPI's response operation schema and additionalProperties representation for the typed dictionary.",
                feature_ids=["openapi-docs", "response-serialization"],
                observation_selectors=["http.status", "openapi.document"],
            ),
        },
    ),
    "tests/test_tutorial/test_generate_clients/test_tutorial001.py": _module(
        [
            {
                "path": "docs_src/generate_clients/tutorial001_py310.py",
                "start_line": 1,
                "end_line": 26,
                "role": "Item input and response models with POST/GET routes",
            },
            {
                "path": "fastapi/dependencies/utils.py",
                "start_line": 951,
                "end_line": 1005,
                "role": "FastAPI request-body extraction and validation integration",
            },
            {
                "path": "fastapi/routing.py",
                "start_line": 301,
                "end_line": 342,
                "role": "FastAPI response-model serialization and filtering",
            },
            {
                "path": "fastapi/openapi/utils.py",
                "start_line": 585,
                "end_line": 647,
                "role": "FastAPI OpenAPI document generation",
            },
        ],
        {
            "test_post_items": _case(
                "tests/test_tutorial/test_generate_clients/test_tutorial001.py",
                20,
                23,
                ["request-validation", "response-serialization"],
                ["http.status", "http.body.json"],
                "FastAPI validates the Item body and applies ResponseMessage as response_model. The fixed response message is application-owned; Pydantic owns Item model semantics.",
            ),
            "test_get_items": _case(
                "tests/test_tutorial/test_generate_clients/test_tutorial001.py",
                26,
                32,
                ["app-routing", "response-serialization"],
                ["http.status", "http.body.json"],
                "FastAPI validates/serializes the list through list[Item]; the list values are application-owned and model serialization details are Pydantic-owned.",
            ),
            "test_openapi_schema": _openapi(
                "tests/test_tutorial/test_generate_clients/test_tutorial001.py",
                35,
                153,
                "The exact schema snapshot checks FastAPI's input/output operation document for generated clients; component JSON Schema details are Pydantic-owned.",
                feature_ids=["openapi-docs", "request-validation", "response-serialization"],
                observation_selectors=["http.status", "openapi.document"],
            ),
        },
    ),
    "tests/test_tutorial/test_generate_clients/test_tutorial002.py": _module(
        [
            {
                "path": "docs_src/generate_clients/tutorial002_py310.py",
                "start_line": 1,
                "end_line": 36,
                "role": "tagged Item/User routes and response models",
            },
            {
                "path": "fastapi/dependencies/utils.py",
                "start_line": 951,
                "end_line": 1005,
                "role": "FastAPI request-body extraction and validation integration",
            },
            {
                "path": "fastapi/routing.py",
                "start_line": 301,
                "end_line": 342,
                "role": "FastAPI response-model serialization and filtering",
            },
            {
                "path": "fastapi/openapi/utils.py",
                "start_line": 585,
                "end_line": 647,
                "role": "FastAPI OpenAPI document generation",
            },
        ],
        {
            "test_post_items": _case(
                "tests/test_tutorial/test_generate_clients/test_tutorial002.py",
                9,
                12,
                ["request-validation", "response-serialization"],
                ["http.status", "http.body.json"],
                "FastAPI validates the Item body and applies ResponseMessage as response_model; the response message is application-owned.",
            ),
            "test_post_users": _case(
                "tests/test_tutorial/test_generate_clients/test_tutorial002.py",
                15,
                20,
                ["request-validation", "response-serialization"],
                ["http.status", "http.body.json"],
                "FastAPI validates the User body and applies ResponseMessage as response_model; the response message is application-owned.",
            ),
            "test_get_items": _case(
                "tests/test_tutorial/test_generate_clients/test_tutorial002.py",
                23,
                29,
                ["app-routing", "response-serialization"],
                ["http.status", "http.body.json"],
                "FastAPI validates/serializes the result through list[Item]; item data is application-owned and Pydantic owns model semantics.",
            ),
            "test_openapi_schema": _openapi(
                "tests/test_tutorial/test_generate_clients/test_tutorial002.py",
                32,
                198,
                "The snapshot checks tagged routes and input/output operation schemas; FastAPI owns operation assembly while Pydantic owns model components.",
                feature_ids=["openapi-docs", "request-validation", "response-serialization"],
                observation_selectors=["http.status", "openapi.document"],
            ),
        },
    ),
    "tests/test_tutorial/test_generate_clients/test_tutorial003.py": _module(
        [
            {
                "path": "docs_src/generate_clients/tutorial003_py310.py",
                "start_line": 1,
                "end_line": 42,
                "role": "custom operation ID generation and tagged Item/User routes",
            },
            {
                "path": "fastapi/routing.py",
                "start_line": 1013,
                "end_line": 1028,
                "role": "FastAPI applies custom unique ID generation to route records",
            },
            {
                "path": "fastapi/openapi/utils.py",
                "start_line": 287,
                "end_line": 308,
                "role": "FastAPI emits route operation IDs in OpenAPI",
            },
            {
                "path": "fastapi/dependencies/utils.py",
                "start_line": 951,
                "end_line": 1005,
                "role": "FastAPI request-body extraction and validation integration",
            },
            {
                "path": "fastapi/routing.py",
                "start_line": 301,
                "end_line": 342,
                "role": "FastAPI response-model serialization and filtering",
            },
            {
                "path": "fastapi/openapi/utils.py",
                "start_line": 585,
                "end_line": 647,
                "role": "FastAPI OpenAPI document generation",
            },
        ],
        {
            "test_post_items": _case(
                "tests/test_tutorial/test_generate_clients/test_tutorial003.py",
                9,
                12,
                ["request-validation", "response-serialization"],
                ["http.status", "http.body.json"],
                "The request and response models are processed by FastAPI; this HTTP test does not observe the custom operation-ID generator.",
            ),
            "test_post_users": _case(
                "tests/test_tutorial/test_generate_clients/test_tutorial003.py",
                15,
                20,
                ["request-validation", "response-serialization"],
                ["http.status", "http.body.json"],
                "The request and response models are processed by FastAPI; this HTTP test does not observe the custom operation-ID generator.",
            ),
            "test_get_items": _case(
                "tests/test_tutorial/test_generate_clients/test_tutorial003.py",
                23,
                29,
                ["app-routing", "response-serialization"],
                ["http.status", "http.body.json"],
                "FastAPI applies the list[Item] response_model; returned item values are application-owned. The custom operation-ID generator is not observed by this request.",
            ),
            "test_openapi_schema": _openapi(
                "tests/test_tutorial/test_generate_clients/test_tutorial003.py",
                32,
                198,
                "The exact document snapshot includes the custom operation IDs generated from route tags and names; operation-ID composition is FastAPI-owned, model component details are Pydantic-owned.",
                feature_ids=["openapi-docs", "request-validation", "response-serialization"],
                observation_selectors=["http.status", "openapi.document"],
            ),
        },
    ),
}
