#!/usr/bin/env python3
"""Render the locked Rust workspace dependency and license inventory."""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs" / "RUST_TARGET_DEPENDENCIES.md"


def cargo_metadata(*, offline: bool) -> dict[str, Any]:
    command = [
        "cargo",
        "metadata",
        "--locked",
        "--format-version",
        "1",
        "--features",
        "pyo3/extension-module",
    ]
    if offline:
        command.append("--offline")
    result = subprocess.run(
        command,
        cwd=ROOT,
        check=False,
        capture_output=True,
        text=True,
    )
    if result.returncode:
        raise RuntimeError(result.stderr.strip() or "cargo metadata failed")
    return json.loads(result.stdout)


def markdown_cell(value: object) -> str:
    return " ".join(str(value or "—").split()).replace("|", "\\|")


def render(metadata: dict[str, Any]) -> str:
    packages = {package["id"]: package for package in metadata["packages"]}
    nodes = {node["id"]: node for node in metadata["resolve"]["nodes"]}
    rows: list[str] = []

    for package_id, package in sorted(
        packages.items(), key=lambda pair: (pair[1]["name"], pair[1]["version"])
    ):
        node = nodes.get(package_id)
        if node is None:
            continue
        package_id_label = f"{package['name']} {package['version']}"
        features = ", ".join(sorted(node["features"])) or "—"
        targets = (
            ", ".join(sorted({kind for target in package["targets"] for kind in target["kind"]}))
            or "—"
        )
        language = "Rust"
        if "proc-macro" in targets:
            language = "Rust proc macro"
        elif "build-script" in targets:
            language = "Rust build script"
        source = "registry"
        if package["source"] is None:
            source = "workspace/path"
        license_value = package.get("license")
        if not license_value and package.get("license_file"):
            license_value = f"file: {package['license_file']}"
        edges: list[str] = []
        for dependency in sorted(node["deps"], key=lambda item: item["name"]):
            target = packages[dependency["pkg"]]
            edge_name = f"{target['name']} {target['version']}"
            kinds = sorted({dep_kind["kind"] or "normal" for dep_kind in dependency["dep_kinds"]})
            if kinds != ["normal"]:
                edge_name += f" ({', '.join(kinds)})"
            edges.append(edge_name)
        rows.append(
            "| "
            + " | ".join(
                markdown_cell(value)
                for value in (
                    package_id_label,
                    license_value or "UNSPECIFIED",
                    language,
                    source,
                    features,
                    package.get("description") or "No Cargo package description",
                    ", ".join(edges) or "—",
                )
            )
            + " |"
        )

    return f"""# FastAPI-RS Rust dependency inventory

This report is generated by `scripts/render_rust_target_dependency_inventory.py`
from `cargo metadata --locked --format-version 1 --features
pyo3/extension-module`. It describes the current Cargo.lock graph, including the
local Starlette-RS path dependency and the extension-module feature used by
Maturin. Regenerate after changing a Cargo manifest or the lockfile. The lock
snapshot is [`Cargo.lock`](../Cargo.lock); a local Starlette-RS checkout is
required to resolve the path dependency.

## Direct use in the project

| Dependency | Declared by | Current purpose and source evidence |
| --- | --- | --- |
| `starlette-rs` 0.1.0 | `fastapi-rs` normal dependency | Rust integration edge to the separately maintained Starlette replacement. FastAPI-RS currently imports `AsgiScopeKind` and `classify_scope` in `fastapi-rs/src/lib.rs`; this is only the foundation and does not provide the FastAPI runtime. |
| `pyo3` 0.29.2 | `fastapi-rs-py` normal dependency | Python/Rust binding API for the extension module, Python exceptions, dictionaries, and module registration in `fastapi-rs-py/src/lib.rs`. `abi3-py310` sets the stable Python ABI minimum; Maturin enables `pyo3/extension-module` from `pyproject.toml`. |
| `pyo3-build-config` 0.29.2 | `fastapi-rs-py` build dependency | PyO3 linker configuration invoked by `fastapi-rs-py/build.rs` so the Rust cdylib is linked as a Python extension. |
| `flate2` 1.1.10 | Starlette-RS normal dependency | Starlette-RS gzip middleware in `starlette-rs/src/gzip.rs`; enables `zlib` with default features disabled, selecting `libz-sys` and its native zlib backend. |
| `serde_json` 1.0.151 | Starlette-RS normal dependency | JSON protocol parsing and output in `starlette-rs/src/bin/starlette-rs-parity-adapter.rs`. |
| `sha2` 0.10.9 | Starlette-RS normal dependency | SHA-256 dependency-lock identity check in the same parity adapter. |

Starlette-RS's adapter dependencies are in the path crate's normal dependency
set, so they appear in this workspace lock graph. The adapter uses Rust; the
zlib path additionally links the platform C zlib library. The `cc`, `pkg-config`,
and `vcpkg` crates support native zlib discovery/building. Transitive crates
below PyO3 provide Python C-API bindings, procedural macros, Rust syntax/token
processing, and their helper routines; each exact edge is listed below.

## Complete locked package graph

Cargo metadata reports every resolved workspace/registry package, selected
feature, package license expression, Cargo target kind, description, and its
immediate dependency edges. Following the edge column recursively from the
three project crates above gives the full transitive closure, including
build-time crates. Cargo license expressions are preserved verbatim; `OR`
means the distributor may satisfy either license, while `AND` requires both.

| Package | Cargo license expression/file | Language/target | Source | Enabled features | Package purpose | Depends on |
| --- | --- | --- | --- | --- | --- | --- |
{chr(10).join(rows)}

## Python package dependencies

The Python distribution declares `pydantic>=2.9.0,<3` and
`starlette-rs-py==0.1.0` in `pyproject.toml`; the selected oracle profile uses
Pydantic 2.13.4. Pydantic's Python package builds schemas and exposes model
behavior, while `pydantic-core` supplies its Rust validation/serialization
engine. `starlette-rs-py` is a separate Rust/Python package and declares AnyIO
`>=3.6.2,<5` in its own manifest. Maturin 1.14.1 is the Python build-system
dependency. These target Python requirements are ranges or package pins, not a
FastAPI-RS Python lockfile; the FastAPI 0.141.1 oracle closure is separately
locked and documented in [`DEPENDENCY_GRAPH.md`](DEPENDENCY_GRAPH.md).

The application-level language boundary is therefore Python package code for
Pydantic models and user-facing Python API behavior, Rust for the FastAPI and
Starlette implementation cores and `pydantic-core`, and PyO3 for the native
module boundary. The current FastAPI-RS Python package is still only a scaffold.
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--offline", action="store_true")
    args = parser.parse_args()
    try:
        output = render(cargo_metadata(offline=args.offline))
    except (RuntimeError, json.JSONDecodeError) as error:
        print(f"dependency inventory failed: {error}", file=sys.stderr)
        return 1
    OUTPUT.write_text(output, encoding="utf-8")
    print(f"wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
