[package]
name = "fastapi-rs"
version.workspace = true
edition.workspace = true
license-file = "../LICENSE.md"
rust-version.workspace = true
repository.workspace = true
description = "Rust implementation core for the FastAPI replacement"
readme = "../README.md"
build = "build.rs"

[features]
default = []
fault-injection = []

[lib]
name = "fastapi_rs"

[dependencies]
base64.workspace = true
pyo3.workspace = true
starlette-rs.workspace = true

[lints]
workspace = true
